### ISSUE TITLE
Issue in readme .repositories[0].prefixes: should be array

### ISSUE THREAD

**Issue by delfer** [pascalgn/simple-repository-manager#1]
Hello!
Thank you for this project! Example in Readme not working:
```
▶ docker run -d -p 3000:3000 --name simple-repository-manager pascalgn/simple-repository-manager
▶ docker logs simple-repository-manager
Error: .repositories[0].prefixes: should be array
    at parseConfig (/usr/local/share/.config/yarn/global/node_modules/simple-repository-manager/src/config.js:28:11)
    at async main (/usr/local/share/.config/yarn/global/node_modules/simple-repository-manager/src/main.js:34:18)
```

**Comment by pascalgn** [comment]
This should be fixed now!
